# Generated by Django 3.0.4 on 2020-04-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
